<?php
if (! defined('ABSPATH')) {
    exit;
}

/**
 * All plugin constants (option names, webhook name, Svelta URLs, etc.).
 */

// Webhook name shown in WooCommerce → Settings → Advanced → Webhooks.
if (! defined('SVELTA_WEBHOOK_NAME')) {
    define('SVELTA_WEBHOOK_NAME', 'Svelta Webhook');
}

// Where we store values returned by Svelta after login.
if (! defined('SVELTA_OPTION_API_KEY')) {
    define('SVELTA_OPTION_API_KEY', 'svelta_api_key');
}
if (! defined('SVELTA_OPTION_CALLBACK_URL')) {
    define('SVELTA_OPTION_CALLBACK_URL', 'svelta_callback_url');
}
if (! defined('SVELTA_OPTION_WEBHOOK_ID')) {
    define('SVELTA_OPTION_WEBHOOK_ID', 'svelta_webhook_id');
}
if (! defined('SVELTA_OPTION_WEBHOOK_LAST_ERROR')) {
    define('SVELTA_OPTION_WEBHOOK_LAST_ERROR', 'svelta_webhook_last_error');
}

// Site-specific key generated by this plugin to identify this store to Svelta.
if (! defined('SVELTA_OPTION_SITE_KEY')) {
    define('SVELTA_OPTION_SITE_KEY', 'svelta_site_api_key');
}

// Which WooCommerce order status should trigger the Svelta webhook.
if (! defined('SVELTA_OPTION_TRIGGER_STATUS')) {
    define('SVELTA_OPTION_TRIGGER_STATUS', 'svelta_trigger_status');
}

// Where we store the WooCommerce REST API key that Svelta will use.
if (! defined('SVELTA_OPTION_REST_KEY_ID')) {
    define('SVELTA_OPTION_REST_KEY_ID', 'svelta_wc_rest_key_id');
}
if (! defined('SVELTA_OPTION_REST_CONSUMER_KEY')) {
    define('SVELTA_OPTION_REST_CONSUMER_KEY', 'svelta_wc_rest_consumer_key');
}
if (! defined('SVELTA_OPTION_REST_CONSUMER_SECRET')) {
    define('SVELTA_OPTION_REST_CONSUMER_SECRET', 'svelta_wc_rest_consumer_secret');
}

// Svelta Delivery API endpoints (used by the order-level card).
if (! defined('SVELTA_BACKEND_DR_STATUS_URL')) {
    define(
        'SVELTA_BACKEND_DR_STATUS_URL',
        'https://staging.clientapi.sveltacourier.com/api/WooCommerceDelivery/Status'
    );
}
if (! defined('SVELTA_BACKEND_DR_CREATE_URL')) {
    define(
        'SVELTA_BACKEND_DR_CREATE_URL',
        'https://staging.clientapi.sveltacourier.com/api/WooCommerceDelivery/Create'
    );
}
if (! defined('SVELTA_BACKEND_DR_CANCEL_URL')) {
    define(
        'SVELTA_BACKEND_DR_CANCEL_URL',
        'https://staging.clientapi.sveltacourier.com/api/WooCommerceDelivery/Cancel'
    );
}

// Svelta Auth endpoint where we send WooCommerce REST credentials.
if (! defined('SVELTA_BACKEND_RECEIVE_CREDS_URL')) {
    define(
        'SVELTA_BACKEND_RECEIVE_CREDS_URL',
        'https://staging.clientapi.sveltacourier.com/api/WooCommerceAuth/ReceivePluginCredentials'
    );
}

// Svelta "Start" URL (auth flow entry point).
if (! defined('SVELTA_START_BASE_URL')) {
    define(
        'SVELTA_START_BASE_URL',
        'https://staging.clientapi.sveltacourier.com/api/WooCommerceAuth/Start?store_url='
    );
}
